### ISSUE TITLE
Use the default Kubeconfig or allow using it

### ISSUE THREAD

**Issue by NasAmin** [WyriHaximus/github-action-helm3#18]
Hi,

First of all, thanks for creating this action!
I have tried to use this action where I am deploying to an EKS cluster. So I am using other actions that sets up aws credentials and kubernetes clusters like these
```
      - name: Configure AWS credentials for EKS deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EKS_REGION }}

      - name: Setup kubeconfig
        id: setup-kubeconfig
        run: |
          aws eks --region ${{ secrets.EKS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
```

However, the entrypoint.sh script seems to be always overwriting the contents of the default kubeconfig.
Can we make than optional and use a flag like `USE_DEFAULT_KUBECONFIG=false`.
So we can then override this flag and set it to true.
If true then we skip creating the kubeconfig and also the cleanup.

Is that doable?

Regards,

Nas

**Comment by WyriHaximus** [comment]
Did some research in #19 and there are a few options. A) you grab the file from the filesystem and pass it into the action, or B) you put it in `./` (your workspace directory). Since this action runs a Docker container it doesn't have access to the default `~/` (`/home/runner/`) but instead has access to the workspaces you're in by default.

You can try option B out with:

```yaml
      - run: mkdir ./.kube -p || true
      - run: cp ~/.kube/config ./.kube/
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@use-existing-kubeconfig-when-available
        with:
          exec: helm COMMAND
      - run: rm ./.kube/config -fR
```
