### ISSUE TITLE
how to avoid using existing kubeconfig file and always use kubeconfig which passed via workflow

### ISSUE THREAD

**Issue by sushovan23** [WyriHaximus/github-action-helm3#70]
Im using following in my workflow:
```
      - name: Dry Run on Ashburn
        id: dry_run_ashburn
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |
            helm upgrademyapp --install --wait --atomic  -f values-resources.yaml --dry-run
          kubeconfig: '${{ env.KUBECONFIG }}'
```

seeing following in run:
```
Existing kubeconfig found, using that and ignoring input
Preparing helm execution
Executing helm
```

how to force action to use supplied kubeconfig?

**Comment by WyriHaximus** [comment]
Just opened https://github.com/WyriHaximus/github-action-helm3/pull/71 to add this

**Comment by WyriHaximus** [comment]
Just released [`v3.1`](https://github.com/WyriHaximus/github-action-helm3/releases/tag/v3.1.0), you can overrule the existing kubeconfig like this:

```yaml
      - name: Dry Run on Ashburn
        id: dry_run_ashburn
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |
            helm upgrademyapp --install --wait --atomic  -f values-resources.yaml --dry-run
          kubeconfig: '${{ env.KUBECONFIG }}'
          overrule_existing_kubeconfig: "true"
```
